import {
  AlertTriangle,
  ArrowRight,
  ArrowLeft,
  ArrowUpRight,
  BookOpen,
  Check,
  ChevronLeft,
  ChevronRight,
  Copy,
  File,
  FileText,
  HelpCircle,
  Home,
  Image,
  Laptop,
  LayoutPanelLeft,
  LineChart,
  Loader2,
  MessagesSquare,
  Moon,
  MoreVertical,
  Package,
  Plus,
  Puzzle,
  Search,
  Settings,
  Star,
  SunMedium,
  User,
  X,
  ChevronDown,
  MessageSquare,
  LayoutGrid,
  List,
  Pencil,
  ThumbsUp,
  LogOut,
  Info,
  Trash,
  Users,
  UserCheck,
  Store,
  Phone,
  Camera,
  Send,
  MessageSquarePlus,
  CornerDownRight,
  Tag,
  Upload,
  AlertCircle,
  CreditCard,
  Lock,
  Eye,
  EyeOff,
  LogIn,
  Mail,
  MailCheck,
} from "lucide-react";

export const Icons = {
  add: Plus,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  arrowUpRight: ArrowUpRight,
  billing: CreditCard,
  bookOpen: BookOpen,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  check: Check,
  close: X,
  copy: Copy,
  dashboard: LayoutPanelLeft,
  ellipsis: MoreVertical,
  help: HelpCircle,
  home: Home,
  laptop: Laptop,
  lineChart: LineChart,
  logo: Puzzle,
  media: Image,
  messages: MessagesSquare,
  moon: Moon,
  package: Package,
  page: File,
  post: FileText,
  search: Search,
  settings: Settings,
  spinner: Loader2,
  sun: SunMedium,
  thumbsUp: ThumbsUp,
  helpCircle: HelpCircle,
  X: X,
  user: User,
  warning: AlertTriangle,
  messageSquare: MessageSquare,
  layoutGrid: LayoutGrid,
  list: List,
  pencil: Pencil,
  logOut: LogOut,
  chevronDown: ChevronDown,
  info: Info,
  star: Star,
  trash: Trash,
  users: Users,
  userCheck: UserCheck,
  store: Store,
  phone: Phone,
  camera: Camera,
  send: Send,
  messagePlus: MessageSquarePlus,
  cornerDownRight: CornerDownRight,
  tag: Tag,
  upload: Upload,
  alertCircle: AlertCircle,
  creditCard: CreditCard,
  lock: Lock,
  eye: Eye,
  eyeOff: EyeOff,
  logIn: LogIn,
  mail: Mail,
  mailCheck: MailCheck,
} as const;

export type Icon = keyof typeof Icons;
